title: Hikerpig's Wiki
theme: jekyll-theme-primer

baseurl: /

exclude:
  - bin
  - _scripts

highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

readme_index:
  enabled:          true
  remove_originals: true

algolia:
  application_id: 'BEYC57071H'
  index_name: "hikerpig's wiki"
  api_key: "a6010aa6141bab85d463363b8865eb27"

plugins:
- jekyll-optional-front-matter
- jekyll-readme-index
- jekyll-default-layout
- jekyll-titles-from-headings
- jekyll-relative-links
